name: Vault CI (User)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Markdownlint CLI
        run: npm install -g markdownlint-cli

      - name: Lint Main Vault
        run: |
          markdownlint --config .markdownlint.json \
            '10 - Fleeting & Daily/**/*.md' \
            '20 - Projects/**/*.md' \
            '30 - Areas/**/*.md' \
            '40 - Resources/**/*.md' \
            '50 - Archives/**/*.md' \
            '99 - Meta & Attachments/**/*.md'

      - name: Lint Docs
        run: markdownlint --config docs/.markdownlint.json 'docs/**/*.md'

      - name: Lint Templates
        run: markdownlint --config '90 - Templates/.markdownlint.json' '90 - Templates/**/*.md'
